package ui.domotica.persiana;

import java.util.Hashtable;
import javax.swing.JLabel;
import ui.Main;
import ui.Modelo;

/**
 * @author Rebeca Hernando Brecht.
 * @author Juan Herruzo Herrero.
 */
public class VistaPersiana extends javax.swing.JFrame {

    // El tamaño del slider es de 8 px extra por cada lado, por lo que para 
    // hacer cálculos precisos de posición necesitamos evitarlos.
    private final int TAM_EXTRA_SLIDER = 8;

    private ControladorPersiana controlador;
    private Modelo modelo;

    public VistaPersiana() {
        initComponents();

        modelo = Main.getStateMachineDomotica().getModelo();
        controlador = new ControladorPersiana(this, modelo);
        crearAltura();
        actualizaAltura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCentral = new javax.swing.JPanel();
        jPanelInfo = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jButtonMas1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonBajar1 = new javax.swing.JButton();
        jButtonSubir1 = new javax.swing.JButton();
        jButtonMenos1 = new javax.swing.JButton();
        jPanelControl = new javax.swing.JPanel();
        jSlider2 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jButtonMas2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonBajar2 = new javax.swing.JButton();
        jButtonSubir2 = new javax.swing.JButton();
        jButtonMenos2 = new javax.swing.JButton();
        jLabelPersiana1 = new javax.swing.JLabel();
        jLabelPersiana2 = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jButtonCalefaccion = new javax.swing.JButton();
        jButtonLuz = new javax.swing.JButton();
        jButtonPersiana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 310));
        setResizable(false);

        jPanel4.setMinimumSize(new java.awt.Dimension(650, 40));
        jPanel4.setName(""); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButtonHome.setBackground(new java.awt.Color(100, 239, 100));
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/home.png"))); // NOI18N
        jButtonHome.setMaximumSize(new java.awt.Dimension(94, 60));
        jButtonHome.setMinimumSize(new java.awt.Dimension(94, 60));
        jButtonHome.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonHome, java.awt.BorderLayout.LINE_START);

        jLabelTitulo.setBackground(new java.awt.Color(138, 253, 138));
        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Persianas");
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(51, 70));
        jLabelTitulo.setOpaque(true);
        jPanel4.add(jLabelTitulo, java.awt.BorderLayout.CENTER);

        jPanelCentral.setPreferredSize(new java.awt.Dimension(650, 358));

        jPanelInfo.setMinimumSize(new java.awt.Dimension(220, 300));
        jPanelInfo.setPreferredSize(new java.awt.Dimension(220, 300));
        jPanelInfo.setLayout(new java.awt.GridLayout(0, 2));

        jSlider1.setMajorTickSpacing(5);
        jSlider1.setMaximum(10);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSlider1MousePressed(evt);
            }
        });
        jPanelInfo.add(jSlider1);

        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        jButtonMas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/mas.png"))); // NOI18N
        jButtonMas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMas1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonMas1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jButtonBajar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/bajar.png"))); // NOI18N
        jButtonBajar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajar1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonBajar1);

        jButtonSubir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/subir.png"))); // NOI18N
        jButtonSubir1.setMaximumSize(new java.awt.Dimension(60, 25));
        jButtonSubir1.setMinimumSize(new java.awt.Dimension(60, 25));
        jButtonSubir1.setPreferredSize(new java.awt.Dimension(60, 25));
        jButtonSubir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubir1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonSubir1);

        jPanel3.add(jPanel5);

        jButtonMenos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/menos.png"))); // NOI18N
        jButtonMenos1.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonMenos1.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonMenos1.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonMenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenos1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonMenos1);

        jPanelInfo.add(jPanel3);

        jPanelControl.setMinimumSize(new java.awt.Dimension(220, 300));
        jPanelControl.setPreferredSize(new java.awt.Dimension(220, 300));
        jPanelControl.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        jSlider2.setMajorTickSpacing(5);
        jSlider2.setMaximum(10);
        jSlider2.setMinorTickSpacing(1);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);
        jSlider2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider2MouseDragged(evt);
            }
        });
        jSlider2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSlider2MousePressed(evt);
            }
        });
        jPanelControl.add(jSlider2);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 10, 10));

        jButtonMas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/mas.png"))); // NOI18N
        jButtonMas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMas2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMas2);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jButtonBajar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/bajar.png"))); // NOI18N
        jButtonBajar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajar2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonBajar2);

        jButtonSubir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/subir.png"))); // NOI18N
        jButtonSubir2.setMaximumSize(new java.awt.Dimension(60, 25));
        jButtonSubir2.setMinimumSize(new java.awt.Dimension(60, 25));
        jButtonSubir2.setPreferredSize(new java.awt.Dimension(60, 25));
        jButtonSubir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubir2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSubir2);

        jPanel1.add(jPanel6);

        jButtonMenos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/menos.png"))); // NOI18N
        jButtonMenos2.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonMenos2.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonMenos2.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonMenos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenos2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenos2);

        jPanelControl.add(jPanel1);

        jLabelPersiana1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPersiana1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPersiana1.setText("Persiana 1");

        jLabelPersiana2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPersiana2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPersiana2.setText("Persiana 2");

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPersiana1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jLabelPersiana2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPersiana1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPersiana2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        jPanelBotones.setMinimumSize(new java.awt.Dimension(650, 40));
        jPanelBotones.setPreferredSize(new java.awt.Dimension(650, 60));
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 3, 12, 0));

        jButtonCalefaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/calefaccion.png"))); // NOI18N
        jButtonCalefaccion.setMaximumSize(new java.awt.Dimension(210, 60));
        jButtonCalefaccion.setMinimumSize(new java.awt.Dimension(210, 60));
        jButtonCalefaccion.setPreferredSize(new java.awt.Dimension(210, 60));
        jButtonCalefaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalefaccionActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonCalefaccion);

        jButtonLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/luz.png"))); // NOI18N
        jButtonLuz.setMaximumSize(new java.awt.Dimension(210, 60));
        jButtonLuz.setMinimumSize(new java.awt.Dimension(210, 60));
        jButtonLuz.setPreferredSize(new java.awt.Dimension(210, 60));
        jButtonLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuzActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonLuz);

        jButtonPersiana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/persiana.png"))); // NOI18N
        jButtonPersiana.setEnabled(false);
        jButtonPersiana.setMaximumSize(new java.awt.Dimension(210, 60));
        jButtonPersiana.setMinimumSize(new java.awt.Dimension(210, 60));
        jButtonPersiana.setPreferredSize(new java.awt.Dimension(210, 60));
        jButtonPersiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersianaActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonPersiana);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuzActionPerformed
        controlador.luz();
    }//GEN-LAST:event_jButtonLuzActionPerformed

    private void jButtonMas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMas2ActionPerformed
        controlador.cambiarPersianas(1, modelo.persiana[1].getAltura() + 1);
    }//GEN-LAST:event_jButtonMas2ActionPerformed

    private void jButtonSubir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubir2ActionPerformed
        controlador.cambiarPersianas(1, 10);
    }//GEN-LAST:event_jButtonSubir2ActionPerformed

    private void jButtonCalefaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalefaccionActionPerformed
        controlador.calefaccion();
    }//GEN-LAST:event_jButtonCalefaccionActionPerformed

    private void jButtonPersianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersianaActionPerformed
        controlador.persiana();
    }//GEN-LAST:event_jButtonPersianaActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        controlador.home();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonMenos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenos2ActionPerformed
        controlador.cambiarPersianas(1, modelo.persiana[1].getAltura() - 1);
    }//GEN-LAST:event_jButtonMenos2ActionPerformed

    private void jButtonBajar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajar2ActionPerformed
        controlador.cambiarPersianas(1, 0);
    }//GEN-LAST:event_jButtonBajar2ActionPerformed

    private void jButtonMas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMas1ActionPerformed
        controlador.cambiarPersianas(0, modelo.persiana[0].getAltura() + 1);
    }//GEN-LAST:event_jButtonMas1ActionPerformed

    private void jButtonMenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenos1ActionPerformed
        controlador.cambiarPersianas(0, modelo.persiana[0].getAltura() - 1);
    }//GEN-LAST:event_jButtonMenos1ActionPerformed

    private void jButtonSubir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubir1ActionPerformed
        controlador.cambiarPersianas(0, 10);
    }//GEN-LAST:event_jButtonSubir1ActionPerformed

    private void jButtonBajar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajar1ActionPerformed
        controlador.cambiarPersianas(0, 0);
    }//GEN-LAST:event_jButtonBajar1ActionPerformed

    private void jSlider2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MousePressed

        controlador.cambiarPersianas(1, posicionSlider(evt.getY()));
    }//GEN-LAST:event_jSlider2MousePressed

    private void jSlider2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MouseDragged

        controlador.cambiarPersianas(1, posicionSlider(evt.getY()));
    }//GEN-LAST:event_jSlider2MouseDragged

    private void jSlider1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MousePressed

        controlador.cambiarPersianas(0, posicionSlider(evt.getY()));
    }//GEN-LAST:event_jSlider1MousePressed

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged

        controlador.cambiarPersianas(0, posicionSlider(evt.getY()));
    }//GEN-LAST:event_jSlider1MouseDragged

    /*Crea las etiquetas de los Sliders*/
    public void crearAltura() {

        Hashtable labelTable = new Hashtable();
        labelTable.put(0, new JLabel("Bajada"));
        labelTable.put(5, new JLabel("Mitad"));
        labelTable.put(10, new JLabel("Subida"));

        jSlider1.setLabelTable(labelTable);
        jSlider2.setLabelTable(labelTable);

        jSlider1.setPaintLabels(true);
        jSlider2.setPaintLabels(true);
    }

    /*Actualiza la posición del Slider*/
    public void actualizaAltura() {
        jSlider1.setValue(modelo.persiana[0].getAltura());
        jSlider2.setValue(modelo.persiana[1].getAltura());
    }

    /*
        Para calcular el valor se quitan los primeros 8 px del slider y los 8 últimos,
        después comprobamos donde se ha pulsado en el slider y se proporciona
        al tamaño del slider.
        
        Como el slider va de abajo a arriba hay que invertir el valor.
    
        Como el jSlider1 y jSlider2 son idénticos se puede usar los valores de uno
        en el otro.
     */
    public int posicionSlider(int y) {
        return jSlider1.getMaximum() - (int) ((jSlider1.getMinimum()
                + ((y - TAM_EXTRA_SLIDER) / ((jSlider1.getHeight() - TAM_EXTRA_SLIDER * 2) * 1.0))
                * (jSlider1.getMaximum() - jSlider1.getMinimum())) + 0.5);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBajar1;
    private javax.swing.JButton jButtonBajar2;
    private javax.swing.JButton jButtonCalefaccion;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLuz;
    private javax.swing.JButton jButtonMas1;
    private javax.swing.JButton jButtonMas2;
    private javax.swing.JButton jButtonMenos1;
    private javax.swing.JButton jButtonMenos2;
    private javax.swing.JButton jButtonPersiana;
    private javax.swing.JButton jButtonSubir1;
    private javax.swing.JButton jButtonSubir2;
    private javax.swing.JLabel jLabelPersiana1;
    private javax.swing.JLabel jLabelPersiana2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    // End of variables declaration//GEN-END:variables
}
