package ui.domotica.luz;

import java.util.Hashtable;
import javax.swing.JLabel;
import ui.Main;
import ui.Modelo;

/**
 *
 * @author Rebeca Hernando Brecht.
 * @author Juan Herruzo Herrero.
 */
public class VistaLuz extends javax.swing.JFrame {

    // El tamaño del slider es de 8 px extra por cada lado, por lo que para 
    // hacer cálculos precisos de posición necesitamos evitarlos.
    private final int TAM_EXTRA_SLIDER = 8;

    private ControladorLuz controlador;
    private Modelo modelo;

    public VistaLuz() {
        initComponents();
        modelo = Main.getStateMachineDomotica().getModelo();
        controlador = new ControladorLuz(this, modelo);
        controlador.iniciarVista();
        crearLuz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPredeterminado = new javax.swing.ButtonGroup();
        buttonGroupLuz = new javax.swing.ButtonGroup();
        buttonGroupColor = new javax.swing.ButtonGroup();
        jPanelTitulo = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCentral = new javax.swing.JPanel();
        jPanelControl = new javax.swing.JPanel();
        jPanelPredeterminados = new javax.swing.JPanel();
        jToggleButtonEncendidas = new javax.swing.JToggleButton();
        jToggleButtonApagadas = new javax.swing.JToggleButton();
        jToggleButtonLectura = new javax.swing.JToggleButton();
        jToggleButtonAmbiente = new javax.swing.JToggleButton();
        jPanelLuzYAjuste = new javax.swing.JPanel();
        jPanelLuces = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jPanelAjustesLuz = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jPanelColores = new javax.swing.JPanel();
        jToggleButtonBlanco = new javax.swing.JToggleButton();
        jToggleButtonAmarillo = new javax.swing.JToggleButton();
        jToggleButtonAzul = new javax.swing.JToggleButton();
        jToggleButtonRojo = new javax.swing.JToggleButton();
        jToggleButtonVerde = new javax.swing.JToggleButton();
        jToggleButtonEncender = new javax.swing.JToggleButton();
        jPanelBotones = new javax.swing.JPanel();
        jButtonCalefaccion = new javax.swing.JButton();
        jButtonLuz = new javax.swing.JButton();
        jButtonPersiana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 310));
        setResizable(false);

        jPanelTitulo.setMinimumSize(new java.awt.Dimension(650, 40));
        jPanelTitulo.setName(""); // NOI18N
        jPanelTitulo.setLayout(new java.awt.BorderLayout());

        jButtonHome.setBackground(new java.awt.Color(255, 255, 153));
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/home.png"))); // NOI18N
        jButtonHome.setMaximumSize(new java.awt.Dimension(94, 60));
        jButtonHome.setMinimumSize(new java.awt.Dimension(94, 60));
        jButtonHome.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanelTitulo.add(jButtonHome, java.awt.BorderLayout.LINE_START);

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 204));
        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Luces");
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(51, 70));
        jLabelTitulo.setOpaque(true);
        jPanelTitulo.add(jLabelTitulo, java.awt.BorderLayout.CENTER);

        jPanelCentral.setPreferredSize(new java.awt.Dimension(650, 358));

        jPanelControl.setPreferredSize(new java.awt.Dimension(220, 300));

        jPanelPredeterminados.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        buttonGroupPredeterminado.add(jToggleButtonEncendidas);
        jToggleButtonEncendidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/enendidas.png"))); // NOI18N
        jToggleButtonEncendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEncendidasActionPerformed(evt);
            }
        });
        jPanelPredeterminados.add(jToggleButtonEncendidas);

        buttonGroupPredeterminado.add(jToggleButtonApagadas);
        jToggleButtonApagadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/apagadas.png"))); // NOI18N
        jToggleButtonApagadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonApagadasActionPerformed(evt);
            }
        });
        jPanelPredeterminados.add(jToggleButtonApagadas);

        buttonGroupPredeterminado.add(jToggleButtonLectura);
        jToggleButtonLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/lectura.png"))); // NOI18N
        jToggleButtonLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLecturaActionPerformed(evt);
            }
        });
        jPanelPredeterminados.add(jToggleButtonLectura);

        buttonGroupPredeterminado.add(jToggleButtonAmbiente);
        jToggleButtonAmbiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/ambiente.png"))); // NOI18N
        jToggleButtonAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAmbienteActionPerformed(evt);
            }
        });
        jPanelPredeterminados.add(jToggleButtonAmbiente);

        buttonGroupLuz.add(jToggleButton1);
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/luzApagada.png"))); // NOI18N
        jToggleButton1.setText("1");
        jToggleButton1.setMaximumSize(new java.awt.Dimension(86, 60));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(86, 60));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(100, 60));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        buttonGroupLuz.add(jToggleButton2);
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/luzApagada.png"))); // NOI18N
        jToggleButton2.setText("2");
        jToggleButton2.setMaximumSize(new java.awt.Dimension(86, 60));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(86, 60));
        jToggleButton2.setPreferredSize(new java.awt.Dimension(100, 60));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroupLuz.add(jToggleButton3);
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/luzApagada.png"))); // NOI18N
        jToggleButton3.setText("3");
        jToggleButton3.setMaximumSize(new java.awt.Dimension(86, 60));
        jToggleButton3.setMinimumSize(new java.awt.Dimension(86, 60));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(100, 60));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        buttonGroupLuz.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/luzApagada.png"))); // NOI18N
        jToggleButton4.setText("4");
        jToggleButton4.setMaximumSize(new java.awt.Dimension(86, 60));
        jToggleButton4.setMinimumSize(new java.awt.Dimension(86, 60));
        jToggleButton4.setPreferredSize(new java.awt.Dimension(100, 60));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        buttonGroupLuz.add(jToggleButton5);
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/luzApagada.png"))); // NOI18N
        jToggleButton5.setText("5");
        jToggleButton5.setMaximumSize(new java.awt.Dimension(86, 60));
        jToggleButton5.setMinimumSize(new java.awt.Dimension(86, 60));
        jToggleButton5.setPreferredSize(new java.awt.Dimension(100, 60));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLucesLayout = new javax.swing.GroupLayout(jPanelLuces);
        jPanelLuces.setLayout(jPanelLucesLayout);
        jPanelLucesLayout.setHorizontalGroup(
            jPanelLucesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLucesLayout.createSequentialGroup()
                .addGroup(jPanelLucesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLucesLayout.createSequentialGroup()
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLucesLayout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanelLucesLayout.setVerticalGroup(
            jPanelLucesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLucesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLucesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLucesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMinimum(1);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSlider1MousePressed(evt);
            }
        });

        jPanelColores.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        buttonGroupColor.add(jToggleButtonBlanco);
        jToggleButtonBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/blanco.png"))); // NOI18N
        jToggleButtonBlanco.setMaximumSize(new java.awt.Dimension(60, 60));
        jToggleButtonBlanco.setMinimumSize(new java.awt.Dimension(60, 60));
        jToggleButtonBlanco.setPreferredSize(new java.awt.Dimension(70, 70));
        jToggleButtonBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBlancoActionPerformed(evt);
            }
        });
        jPanelColores.add(jToggleButtonBlanco);

        buttonGroupColor.add(jToggleButtonAmarillo);
        jToggleButtonAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/amarillo.png"))); // NOI18N
        jToggleButtonAmarillo.setMaximumSize(new java.awt.Dimension(60, 60));
        jToggleButtonAmarillo.setMinimumSize(new java.awt.Dimension(60, 60));
        jToggleButtonAmarillo.setPreferredSize(new java.awt.Dimension(70, 70));
        jToggleButtonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAmarilloActionPerformed(evt);
            }
        });
        jPanelColores.add(jToggleButtonAmarillo);

        buttonGroupColor.add(jToggleButtonAzul);
        jToggleButtonAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/azul.png"))); // NOI18N
        jToggleButtonAzul.setMaximumSize(new java.awt.Dimension(60, 60));
        jToggleButtonAzul.setMinimumSize(new java.awt.Dimension(60, 60));
        jToggleButtonAzul.setPreferredSize(new java.awt.Dimension(70, 70));
        jToggleButtonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAzulActionPerformed(evt);
            }
        });
        jPanelColores.add(jToggleButtonAzul);

        buttonGroupColor.add(jToggleButtonRojo);
        jToggleButtonRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/rojo.png"))); // NOI18N
        jToggleButtonRojo.setMaximumSize(new java.awt.Dimension(60, 60));
        jToggleButtonRojo.setMinimumSize(new java.awt.Dimension(60, 60));
        jToggleButtonRojo.setPreferredSize(new java.awt.Dimension(70, 70));
        jToggleButtonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRojoActionPerformed(evt);
            }
        });
        jPanelColores.add(jToggleButtonRojo);

        buttonGroupColor.add(jToggleButtonVerde);
        jToggleButtonVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/verde.png"))); // NOI18N
        jToggleButtonVerde.setMaximumSize(new java.awt.Dimension(60, 60));
        jToggleButtonVerde.setMinimumSize(new java.awt.Dimension(60, 60));
        jToggleButtonVerde.setPreferredSize(new java.awt.Dimension(70, 70));
        jToggleButtonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVerdeActionPerformed(evt);
            }
        });
        jPanelColores.add(jToggleButtonVerde);

        jToggleButtonEncender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/on_off.png"))); // NOI18N
        jToggleButtonEncender.setMaximumSize(new java.awt.Dimension(60, 60));
        jToggleButtonEncender.setMinimumSize(new java.awt.Dimension(60, 60));
        jToggleButtonEncender.setPreferredSize(new java.awt.Dimension(72, 70));
        jToggleButtonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEncenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAjustesLuzLayout = new javax.swing.GroupLayout(jPanelAjustesLuz);
        jPanelAjustesLuz.setLayout(jPanelAjustesLuzLayout);
        jPanelAjustesLuzLayout.setHorizontalGroup(
            jPanelAjustesLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjustesLuzLayout.createSequentialGroup()
                .addGroup(jPanelAjustesLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAjustesLuzLayout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jToggleButtonEncender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAjustesLuzLayout.setVerticalGroup(
            jPanelAjustesLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjustesLuzLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAjustesLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonEncender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jPanelColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelLuzYAjusteLayout = new javax.swing.GroupLayout(jPanelLuzYAjuste);
        jPanelLuzYAjuste.setLayout(jPanelLuzYAjusteLayout);
        jPanelLuzYAjusteLayout.setHorizontalGroup(
            jPanelLuzYAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLuzYAjusteLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelLuces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAjustesLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLuzYAjusteLayout.setVerticalGroup(
            jPanelLuzYAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLuzYAjusteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelAjustesLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addComponent(jPanelLuces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
        jPanelControl.setLayout(jPanelControlLayout);
        jPanelControlLayout.setHorizontalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLuzYAjuste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addComponent(jPanelPredeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelControlLayout.setVerticalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addComponent(jPanelPredeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLuzYAjuste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBotones.setMinimumSize(new java.awt.Dimension(650, 40));
        jPanelBotones.setPreferredSize(new java.awt.Dimension(650, 60));
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 3, 12, 0));

        jButtonCalefaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/calefaccion.png"))); // NOI18N
        jButtonCalefaccion.setMaximumSize(new java.awt.Dimension(210, 60));
        jButtonCalefaccion.setMinimumSize(new java.awt.Dimension(210, 60));
        jButtonCalefaccion.setPreferredSize(new java.awt.Dimension(210, 60));
        jButtonCalefaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalefaccionActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonCalefaccion);

        jButtonLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/luz.png"))); // NOI18N
        jButtonLuz.setEnabled(false);
        jButtonLuz.setMaximumSize(new java.awt.Dimension(210, 60));
        jButtonLuz.setMinimumSize(new java.awt.Dimension(210, 60));
        jButtonLuz.setPreferredSize(new java.awt.Dimension(210, 60));
        jButtonLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuzActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonLuz);

        jButtonPersiana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/persiana.png"))); // NOI18N
        jButtonPersiana.setMaximumSize(new java.awt.Dimension(210, 60));
        jButtonPersiana.setMinimumSize(new java.awt.Dimension(210, 60));
        jButtonPersiana.setPreferredSize(new java.awt.Dimension(210, 60));
        jButtonPersiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersianaActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonPersiana);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuzActionPerformed
        controlador.luz();
    }//GEN-LAST:event_jButtonLuzActionPerformed

    private void jButtonCalefaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalefaccionActionPerformed
        controlador.calefaccion();
    }//GEN-LAST:event_jButtonCalefaccionActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        controlador.home();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonPersianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersianaActionPerformed
        controlador.persiana();
    }//GEN-LAST:event_jButtonPersianaActionPerformed

    private void jToggleButtonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEncenderActionPerformed
        controlador.encender();
    }//GEN-LAST:event_jToggleButtonEncenderActionPerformed

    private void jToggleButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVerdeActionPerformed
        controlador.guardaColor(1);
    }//GEN-LAST:event_jToggleButtonVerdeActionPerformed

    private void jToggleButtonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRojoActionPerformed
        controlador.guardaColor(4);
    }//GEN-LAST:event_jToggleButtonRojoActionPerformed

    private void jToggleButtonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAzulActionPerformed
        controlador.guardaColor(2);
    }//GEN-LAST:event_jToggleButtonAzulActionPerformed

    private void jToggleButtonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAmarilloActionPerformed
        controlador.guardaColor(3);
    }//GEN-LAST:event_jToggleButtonAmarilloActionPerformed

    private void jToggleButtonBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBlancoActionPerformed
        controlador.guardaColor(0);
    }//GEN-LAST:event_jToggleButtonBlancoActionPerformed

    private void jSlider1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MousePressed
        controlador.actualizaIntensidad(posicionSlider(evt.getX()));
        actualizaVista();
    }//GEN-LAST:event_jSlider1MousePressed

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged
        controlador.actualizaIntensidad(posicionSlider(evt.getX()));
        actualizaVista();
    }//GEN-LAST:event_jSlider1MouseDragged

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        controlador.mostrarBombilla(4);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        controlador.mostrarBombilla(3);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        controlador.mostrarBombilla(2);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        controlador.mostrarBombilla(1);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        controlador.mostrarBombilla(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButtonAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAmbienteActionPerformed
        controlador.botonAmbiente();
    }//GEN-LAST:event_jToggleButtonAmbienteActionPerformed

    private void jToggleButtonLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLecturaActionPerformed
        controlador.botonLectura();
    }//GEN-LAST:event_jToggleButtonLecturaActionPerformed

    private void jToggleButtonApagadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonApagadasActionPerformed
        controlador.botonApagadas();
    }//GEN-LAST:event_jToggleButtonApagadasActionPerformed

    private void jToggleButtonEncendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEncendidasActionPerformed
        controlador.botonEncendidas();
    }//GEN-LAST:event_jToggleButtonEncendidasActionPerformed

    //Llama a todas las funciones que actualiza la vista.
    public void actualizaVista() {
        actualizaColorBombilla();
        actualizaIntensidad();
        actualizaBotonColor();
        actualizaHabilitarColor();
        actualizaApagado();
        actualizaPulsada();
        controlador.actualizaPredeterminado();

    }

    /*
    Actualiza el icono de la bombilla actual acorde a su color.
     */
    public void actualizaColorBombilla() {
        int color = modelo.bombilla[modelo.numBombilla].getColor();
        boolean encendida = modelo.bombilla[modelo.numBombilla].getEncendido();

        String cambio = null;
        if (encendida) {
            switch (color) {
                case 0:
                    cambio = "/ui/assets/luzBlanca.png";
                    break;

                case 1:
                    cambio = "/ui/assets/luzVerde.png";
                    break;

                case 2:
                    cambio = "/ui/assets/luzAzul.png";
                    break;

                case 3:
                    cambio = "/ui/assets/luzAmarilla.png";
                    break;

                case 4:
                    cambio = "/ui/assets/luzRoja.png";
                    break;
            }
        } else {
            cambio = "/ui/assets/luzApagada.png";
        }
        switch (modelo.numBombilla) {
            case 0:
                jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

            case 1:
                jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

            case 2:
                jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

            case 3:
                jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

            case 4:
                jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

        }

    }

    /*
    Actualiza la posición del Slider a la actual de la bombilla. 
     */
    public void actualizaIntensidad() {
        if (modelo.bombilla[modelo.numBombilla].getEncendido()) {
            //si presionan los botones predeterminados cambia el Slider a la intensiadad adecuada.
            jSlider1.setValue(modelo.bombilla[modelo.numBombilla].getIntensidad());
        } else {
            //si presionan los botones predeterminados cambia el Slider a la intensiadad adecuada.
            jSlider1.setValue(1);

        }
    }

    //Hace que los botones de los colores se presionen si dan a los botones predetermiandos de arriba.
    public void actualizaBotonColor() {
        int color = modelo.bombilla[modelo.numBombilla].getColor();
        switch (color) {
            case 0:
                jToggleButtonBlanco.setSelected(true);
                break;

            case 1:
                jToggleButtonVerde.setSelected(true);
                break;

            case 2:
                jToggleButtonAzul.setSelected(true);
                break;

            case 3:
                jToggleButtonAmarillo.setSelected(true);
                break;

            case 4:
                jToggleButtonRojo.setSelected(true);
                break;
            default:
                buttonGroupColor.clearSelection();

        }
    }

    /*
    Permite seleccionar color si la bombilla está encendida.
     */
    public void actualizaHabilitarColor() {
        if (modelo.bombilla[modelo.numBombilla].getEncendido()) {
            jToggleButtonBlanco.setEnabled(true);
            jToggleButtonAmarillo.setEnabled(true);
            jToggleButtonVerde.setEnabled(true);
            jToggleButtonAzul.setEnabled(true);
            jToggleButtonRojo.setEnabled(true);

        } else {
            buttonGroupColor.clearSelection();
            jToggleButtonBlanco.setEnabled(false);
            jToggleButtonAmarillo.setEnabled(false);
            jToggleButtonVerde.setEnabled(false);
            jToggleButtonAzul.setEnabled(false);
            jToggleButtonRojo.setEnabled(false);
        }
    }

    //Si cumple las propiedades los botones predeterminados se activa dicho botón.
    public void activaBotonPredeterminado(String boton) {

        switch (boton) {
            case "encendidas":
                jToggleButtonEncendidas.setSelected(true);
                break;
            case "apagadas":
                jToggleButtonApagadas.setSelected(true);
                break;
            case "lectura":
                jToggleButtonLectura.setSelected(true);
                break;
            case "ambiente":
                jToggleButtonAmbiente.setSelected(true);
                break;
            case "ninguno":
                buttonGroupPredeterminado.clearSelection();
        }
    }

    /*
    Actualiza el estado del boton de apagado dependiendo de si la bombilla está encendida.
     */
    public void actualizaApagado() {
        if (modelo.bombilla[modelo.numBombilla].getEncendido()) {
            jToggleButtonEncender.setSelected(true);
        } else {
            jToggleButtonEncender.setSelected(false);
        }

    }

    /*
    Actualiza que bombilla está seleccionando, es útil para cuando se abre de nuevo el menú de la luz.
     */
    public void actualizaPulsada() {

        switch (modelo.numBombilla) {
            case 0:
                jToggleButton1.setSelected(true);
                break;
            case 1:
                jToggleButton2.setSelected(true);
                break;
            case 2:
                jToggleButton3.setSelected(true);
                break;
            case 3:
                jToggleButton4.setSelected(true);
                break;
            case 4:
                jToggleButton5.setSelected(true);
                break;
            default:
                buttonGroupLuz.clearSelection();
        }
    }

    /*
    Crea las etiquetas personalizadas del slider.
     */
    public void crearLuz() {
        Hashtable labelTable = new Hashtable();
        labelTable.put(1, new JLabel("1"));
        for (int i = 10; i <= 100; i += 10) {
            labelTable.put(i, new JLabel(Integer.toString(i)));
        }

        jSlider1.setLabelTable(labelTable);
        jSlider1.setPaintLabels(true);
    }

    /*
        Para calcular el valor se quitan los primeros 8 px del slider y los 8 últimos,
        después comprobamos donde se ha pulsado en el slider y se proporciona
        al tamaño del slider.
     */
    public int posicionSlider(int x) {
        return (int) ((jSlider1.getMinimum()
                + ((x - TAM_EXTRA_SLIDER) / ((jSlider1.getWidth() - TAM_EXTRA_SLIDER * 2) * 1.0))
                * (jSlider1.getMaximum() - jSlider1.getMinimum())) + 0.5);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColor;
    private javax.swing.ButtonGroup buttonGroupLuz;
    private javax.swing.ButtonGroup buttonGroupPredeterminado;
    private javax.swing.JButton jButtonCalefaccion;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLuz;
    private javax.swing.JButton jButtonPersiana;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelAjustesLuz;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelColores;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelLuces;
    private javax.swing.JPanel jPanelLuzYAjuste;
    private javax.swing.JPanel jPanelPredeterminados;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButtonAmarillo;
    private javax.swing.JToggleButton jToggleButtonAmbiente;
    private javax.swing.JToggleButton jToggleButtonApagadas;
    private javax.swing.JToggleButton jToggleButtonAzul;
    private javax.swing.JToggleButton jToggleButtonBlanco;
    private javax.swing.JToggleButton jToggleButtonEncender;
    private javax.swing.JToggleButton jToggleButtonEncendidas;
    private javax.swing.JToggleButton jToggleButtonLectura;
    private javax.swing.JToggleButton jToggleButtonRojo;
    private javax.swing.JToggleButton jToggleButtonVerde;
    // End of variables declaration//GEN-END:variables
}
