package my.entrega1rebhernjuaherrVista;

import java.awt.Color;
import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JToggleButton;
import my.entrega1rebhernjuaherrModelo.ModeloEntrega;

/**
 *
 * @author Rebeca Hernando Brecht.
 * @author Juan Herruzo Herrero.
 */
public class VistaEntrega extends javax.swing.JFrame {

    private ControladorEntrega controlador;
    private ModeloEntrega modelo;

    /**
     * Creates new form VistaEntrega
     */
    public VistaEntrega() {
        initComponents();
        modelo = new ModeloEntrega();
        controlador = new ControladorEntrega(this, modelo);

        controlador.botonApagadas();
        jToggleButtonEncendidas.setBackground(Color.WHITE);

        jToggleButton1.setToolTipText("Puede ser usado con ALT + 1");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanelMasColores = new javax.swing.JPanel();
        jLabelImagenColores = new javax.swing.JLabel();
        jButtonAtrasMasColores = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanelPredeterminados = new javax.swing.JPanel();
        jToggleButtonEncendidas = new javax.swing.JToggleButton();
        jToggleButtonApagadas = new javax.swing.JToggleButton();
        jToggleButtonAmbiente = new javax.swing.JToggleButton();
        jToggleButtonLectura = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jPanelLuz = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelPropiedades = new javax.swing.JPanel();
        jPanelInterruptor = new javax.swing.JPanel();
        jToggleButtonEncendido = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelIntensidad = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabelTextoIntensidad = new javax.swing.JLabel();
        jPanelColor = new javax.swing.JPanel();
        jToggleButtonBlanco = new javax.swing.JToggleButton();
        jToggleButtonAmarillo = new javax.swing.JToggleButton();
        jToggleButtonRojo = new javax.swing.JToggleButton();
        jToggleButtonAzul = new javax.swing.JToggleButton();
        jToggleButtonVerde = new javax.swing.JToggleButton();
        jButtonMasColores = new javax.swing.JButton();
        jButtonAmpliarLetra = new javax.swing.JButton();
        jButtonReducirLetra = new javax.swing.JButton();
        jButtonContraste = new javax.swing.JButton();

        jPanelMasColores.setBorder(javax.swing.BorderFactory.createTitledBorder("Elige un color"));

        jLabelImagenColores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/assets/colores.png"))); // NOI18N
        jLabelImagenColores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImagenColoresMouseClicked(evt);
            }
        });

        jButtonAtrasMasColores.setText("Atrás");
        jButtonAtrasMasColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasMasColoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMasColoresLayout = new javax.swing.GroupLayout(jPanelMasColores);
        jPanelMasColores.setLayout(jPanelMasColoresLayout);
        jPanelMasColoresLayout.setHorizontalGroup(
            jPanelMasColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAtrasMasColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMasColoresLayout.setVerticalGroup(
            jPanelMasColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMasColoresLayout.createSequentialGroup()
                .addComponent(jLabelImagenColores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAtrasMasColores, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelPredeterminados.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelos predeterminados."));
        jPanelPredeterminados.setPreferredSize(new java.awt.Dimension(100, 123));
        jPanelPredeterminados.setLayout(new java.awt.GridLayout(1, 4, 5, 10));

        buttonGroup1.add(jToggleButtonEncendidas);
        jToggleButtonEncendidas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jToggleButtonEncendidas.setText("Encendidas");
        jToggleButtonEncendidas.setToolTipText("Sirve para encender todas la luces");
        jToggleButtonEncendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEncendidasActionPerformed(evt);
            }
        });
        jPanelPredeterminados.add(jToggleButtonEncendidas);

        buttonGroup1.add(jToggleButtonApagadas);
        jToggleButtonApagadas.setText("Apagadas");
        jToggleButtonApagadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonApagadasActionPerformed(evt);
            }
        });
        jPanelPredeterminados.add(jToggleButtonApagadas);

        buttonGroup1.add(jToggleButtonAmbiente);
        jToggleButtonAmbiente.setText("Ambiente");
        jToggleButtonAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAmbienteActionPerformed(evt);
            }
        });
        jPanelPredeterminados.add(jToggleButtonAmbiente);

        buttonGroup1.add(jToggleButtonLectura);
        jToggleButtonLectura.setText("Lectura");
        jToggleButtonLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLecturaActionPerformed(evt);
            }
        });
        jPanelPredeterminados.add(jToggleButtonLectura);

        jPanel6.setPreferredSize(new java.awt.Dimension(860, 400));
        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanelLuz.setBorder(javax.swing.BorderFactory.createTitledBorder("Selección de luz"));

        buttonGroup3.add(jToggleButton1);
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/assets/LuzApagada.png"))); // NOI18N
        jToggleButton1.setMnemonic('a');
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jToggleButton2);
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/assets/LuzApagada.png"))); // NOI18N
        jToggleButton2.setMnemonic('2');
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jToggleButton3);
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/assets/LuzApagada.png"))); // NOI18N
        jToggleButton3.setMnemonic('3');
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/assets/LuzApagada.png"))); // NOI18N
        jToggleButton4.setMnemonic('4');
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jToggleButton5);
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/assets/LuzApagada.png"))); // NOI18N
        jToggleButton5.setMnemonic('5');
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Luz 1");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Luz 2");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Luz 3");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Luz 4");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Luz 5");

        javax.swing.GroupLayout jPanelLuzLayout = new javax.swing.GroupLayout(jPanelLuz);
        jPanelLuz.setLayout(jPanelLuzLayout);
        jPanelLuzLayout.setHorizontalGroup(
            jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLuzLayout.createSequentialGroup()
                .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLuzLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLuzLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelLuzLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLuzLayout.createSequentialGroup()
                                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLuzLayout.setVerticalGroup(
            jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLuzLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel6.add(jPanelLuz);

        jPanelPropiedades.setBorder(javax.swing.BorderFactory.createTitledBorder("Propiedades"));
        jPanelPropiedades.setPreferredSize(new java.awt.Dimension(430, 1904));
        jPanelPropiedades.setLayout(new java.awt.GridLayout(1, 2, 0, 5));

        jPanelInterruptor.setBorder(javax.swing.BorderFactory.createTitledBorder("Interruptor"));
        jPanelInterruptor.setLayout(new java.awt.GridLayout(2, 0));

        jToggleButtonEncendido.setText("Encendido");
        jToggleButtonEncendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEncendidoActionPerformed(evt);
            }
        });
        jPanelInterruptor.add(jToggleButtonEncendido);

        jLabelIntensidad.setText("50");

        jSlider1.setMinimum(1);
        jSlider1.setPaintTicks(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSlider1MousePressed(evt);
            }
        });

        jLabelTextoIntensidad.setText("Intensidad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTextoIntensidad)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelIntensidad)
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoIntensidad)
                    .addComponent(jLabelIntensidad))
                .addGap(18, 18, 18)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelInterruptor.add(jPanel1);

        jPanelPropiedades.add(jPanelInterruptor);

        jPanelColor.setBorder(javax.swing.BorderFactory.createTitledBorder("Color"));
        jPanelColor.setLayout(new java.awt.GridLayout(6, 1));

        buttonGroup2.add(jToggleButtonBlanco);
        jToggleButtonBlanco.setText("Blanco");
        jToggleButtonBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBlancoActionPerformed(evt);
            }
        });
        jPanelColor.add(jToggleButtonBlanco);

        buttonGroup2.add(jToggleButtonAmarillo);
        jToggleButtonAmarillo.setText("Amarillo");
        jToggleButtonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAmarilloActionPerformed(evt);
            }
        });
        jPanelColor.add(jToggleButtonAmarillo);

        buttonGroup2.add(jToggleButtonRojo);
        jToggleButtonRojo.setText("Rojo");
        jToggleButtonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRojoActionPerformed(evt);
            }
        });
        jPanelColor.add(jToggleButtonRojo);

        buttonGroup2.add(jToggleButtonAzul);
        jToggleButtonAzul.setText("Azul");
        jToggleButtonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAzulActionPerformed(evt);
            }
        });
        jPanelColor.add(jToggleButtonAzul);

        buttonGroup2.add(jToggleButtonVerde);
        jToggleButtonVerde.setText("Verde");
        jToggleButtonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVerdeActionPerformed(evt);
            }
        });
        jPanelColor.add(jToggleButtonVerde);

        jButtonMasColores.setText("Otro Color");
        jButtonMasColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasColoresActionPerformed(evt);
            }
        });
        jPanelColor.add(jButtonMasColores);

        jPanelPropiedades.add(jPanelColor);

        jPanel6.add(jPanelPropiedades);

        jButtonAmpliarLetra.setText("+");
        jButtonAmpliarLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmpliarLetraActionPerformed(evt);
            }
        });

        jButtonReducirLetra.setText("-");
        jButtonReducirLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReducirLetraActionPerformed(evt);
            }
        });

        jButtonContraste.setText("Contraste");
        jButtonContraste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContrasteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPredeterminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonAmpliarLetra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonReducirLetra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonContraste))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelPredeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonAmpliarLetra)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonReducirLetra)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonContraste)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonEncendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEncendidasActionPerformed
        controlador.botonEncendidas();

    }//GEN-LAST:event_jToggleButtonEncendidasActionPerformed

    private void jToggleButtonApagadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonApagadasActionPerformed
        controlador.botonApagadas();    }//GEN-LAST:event_jToggleButtonApagadasActionPerformed

    private void jToggleButtonAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAmbienteActionPerformed
        controlador.botonAmbiente();
    }//GEN-LAST:event_jToggleButtonAmbienteActionPerformed

    private void jToggleButtonLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLecturaActionPerformed
        controlador.botonLectura();
    }//GEN-LAST:event_jToggleButtonLecturaActionPerformed

    private void jButtonAtrasMasColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasMasColoresActionPerformed
        controlador.mostrarColores(false);
        actualizaBotonColor();

    }//GEN-LAST:event_jButtonAtrasMasColoresActionPerformed

    private void jLabelImagenColoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagenColoresMouseClicked
        controlador.guardaColorImagen(evt.getX(), jLabelImagenColores.getWidth(), evt.getY(), jLabelImagenColores.getHeight());
        controlador.pintaBotonColor();

    }//GEN-LAST:event_jLabelImagenColoresMouseClicked

    private void jToggleButtonBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBlancoActionPerformed
        controlador.guardaColor(0, 0, 1);
        controlador.pintaBotonColor();
    }//GEN-LAST:event_jToggleButtonBlancoActionPerformed

    private void jToggleButtonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAmarilloActionPerformed
        controlador.guardaColor((float) (60 / 360.0), 1, 1);
        controlador.pintaBotonColor();

    }//GEN-LAST:event_jToggleButtonAmarilloActionPerformed

    private void jToggleButtonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRojoActionPerformed
        controlador.guardaColor((float) (0 / 360.0), 1, 1);
        controlador.pintaBotonColor();

    }//GEN-LAST:event_jToggleButtonRojoActionPerformed

    private void jToggleButtonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAzulActionPerformed
        controlador.guardaColor((float) (240 / 360.0), 1, 1);
        controlador.pintaBotonColor();

    }//GEN-LAST:event_jToggleButtonAzulActionPerformed

    private void jToggleButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVerdeActionPerformed
        controlador.guardaColor((float) (120 / 360.0), 1, 1);
        controlador.pintaBotonColor();

    }//GEN-LAST:event_jToggleButtonVerdeActionPerformed

    private void jToggleButtonEncendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEncendidoActionPerformed
        controlador.encender();
    }//GEN-LAST:event_jToggleButtonEncendidoActionPerformed

    private void jButtonMasColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasColoresActionPerformed
        controlador.mostrarColores(true);
    }//GEN-LAST:event_jButtonMasColoresActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        controlador.mostrarBombilla(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        controlador.mostrarBombilla(1);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        controlador.mostrarBombilla(2);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        controlador.mostrarBombilla(3);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        controlador.mostrarBombilla(4);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        controlador.actualizaIntensidad(jSlider1.getValue());
        controlador.pintaIntensidad();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MousePressed
        controlador.encenderIntensidad();
    }//GEN-LAST:event_jSlider1MousePressed

    private void jButtonAmpliarLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmpliarLetraActionPerformed
        controlador.letra(1);
    }//GEN-LAST:event_jButtonAmpliarLetraActionPerformed

    private void jButtonReducirLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReducirLetraActionPerformed
        controlador.letra(-1);
    }//GEN-LAST:event_jButtonReducirLetraActionPerformed

    private void jButtonContrasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContrasteActionPerformed
        controlador.contraste();
    }//GEN-LAST:event_jButtonContrasteActionPerformed
    public void actualizaLetra() {
        actualizaInterno(getComponents());
    }

    private void actualizaInterno(java.awt.Component[] listaComponentes) {
        for (java.awt.Component componente : listaComponentes) {
            if (componente instanceof java.awt.Container) {
                actualizaInterno(((java.awt.Container) componente).getComponents());
            }
            componente.setFont(new java.awt.Font("Dialog", java.awt.Font.BOLD, modelo.tamLetra)); // NOI18N
        }
    }

    public void actualizaContraste() {
        for (java.awt.Component componente : jPanelPredeterminados.getComponents()) {
            if (componente instanceof JToggleButton) {
                componente.setBackground(modelo.contraste ? Color.WHITE : null);
            }
        }
        for (java.awt.Component componente : jPanelColor.getComponents()) {
            if (componente instanceof JToggleButton) {
                componente.setBackground(modelo.contraste ? Color.WHITE : null);
            }
        }
        jToggleButtonEncendido.setBackground(modelo.contraste ? Color.WHITE : null);
    }

    //Llama a todas las funciones que actualiza la vista.
    public void actualizaVista() {
        actualizaColorBombilla();
        actualizaIntensidad();
        actualizaEncendido();
        actualizaBotonColor();
        actualizaHabilitarColor();
        actualizaCuadroColores();
        actualizaSeleccion();
        controlador.actualizaPredeterminado();

    }

    public void actualizaCuadroColores() {
        if (modelo.masColores) {
            jPanelPropiedades.remove(jPanelColor);
            jPanelPropiedades.add(jPanelMasColores);
        } else {
            jPanelPropiedades.remove(jPanelMasColores);
            jPanelPropiedades.add(jPanelColor);
        }
        jPanelPropiedades.revalidate();
        jPanelPropiedades.repaint();

    }

    //No se para qeu usas esto pero te lo he cmabiado de nombre porque
    //actualizaBoton es mu genéricoy me liaba, no da error en ningun lado
    public void actualizaColorBombilla() {
        float hue = modelo.bombilla[modelo.numBombilla].getColor();
        float s = modelo.bombilla[modelo.numBombilla].getSaturacion();
        float b = modelo.bombilla[modelo.numBombilla].getBrillo();

        switch (modelo.numBombilla) {
            case 0:
                jToggleButton1.setBackground(Color.getHSBColor(hue, s, b));
                break;

            case 1:
                jToggleButton2.setBackground(Color.getHSBColor(hue, s, b));
                break;

            case 2:
                jToggleButton3.setBackground(Color.getHSBColor(hue, s, b));
                break;

            case 3:
                jToggleButton4.setBackground(Color.getHSBColor(hue, s, b));
                break;

            case 4:
                jToggleButton5.setBackground(Color.getHSBColor(hue, s, b));
                break;

        }

    }

    public void actualizaSeleccion() {
        switch (modelo.numBombilla) {
            case 0:
                jLabel1.setOpaque(true);
                jLabel2.setOpaque(false);
                jLabel3.setOpaque(false);
                jLabel4.setOpaque(false);
                jLabel5.setOpaque(false);

                break;

            case 1:

                jLabel1.setOpaque(false);
                jLabel2.setOpaque(true);
                jLabel3.setOpaque(false);
                jLabel4.setOpaque(false);
                jLabel5.setOpaque(false);
                break;

            case 2:
                jLabel1.setOpaque(false);
                jLabel2.setOpaque(false);
                jLabel3.setOpaque(true);
                jLabel4.setOpaque(false);
                jLabel5.setOpaque(false);
                break;

            case 3:
                jLabel1.setOpaque(false);
                jLabel2.setOpaque(false);
                jLabel3.setOpaque(false);
                jLabel4.setOpaque(true);
                jLabel5.setOpaque(false);
                break;
            case 4:
                jLabel1.setOpaque(false);
                jLabel2.setOpaque(false);
                jLabel3.setOpaque(false);
                jLabel4.setOpaque(false);
                jLabel5.setOpaque(true);
                break;

        }
        jLabel1.repaint();
        jLabel2.repaint();
        jLabel3.repaint();
        jLabel4.repaint();
        jLabel5.repaint();

    }

    public void actualizaIntensidad() {
        if (modelo.bombilla[modelo.numBombilla].getEncendido()) {
            jLabelIntensidad.setText(Integer.toString(modelo.bombilla[modelo.numBombilla].getIntensidad()));
            //si presionan los botones predeterminados cambia el Slider a la intensiadad adecuada.
            jSlider1.setValue(modelo.bombilla[modelo.numBombilla].getIntensidad());
        } else {
            jLabelIntensidad.setText("1");
            //si presionan los botones predeterminados cambia el Slider a la intensiadad adecuada.
            jSlider1.setValue(1);

        }
    }

    public void actualizaColorEncender() {
        if (modelo.bombilla[modelo.numBombilla].getEncendido()) {
            modelo.bombilla[modelo.numBombilla].setColor(0);
            modelo.bombilla[modelo.numBombilla].setSaturacion(0);
            modelo.bombilla[modelo.numBombilla].setBrillo(1);
        } else {
            modelo.bombilla[modelo.numBombilla].setColor(0);
            modelo.bombilla[modelo.numBombilla].setSaturacion(0);
            modelo.bombilla[modelo.numBombilla].setBrillo(0.5f);
        }

    }

    //Cambia la imagen del boton según esté encendido o apagado.
    public void actualizaEncendido() {
        String cambio;

        if (modelo.bombilla[modelo.numBombilla].getEncendido()) {
            jToggleButtonEncendido.setSelected(true);
            cambio = "/my/assets/LuzEncendida.png";
        } else {

            jToggleButtonEncendido.setSelected(false);
            //además de cambiar la imagen pone el fondo en blanco para que sea
            //más visible que está apagada.
            cambio = "/my/assets/LuzApagada.png";
            actualizaColorBombilla();

        }

        switch (modelo.numBombilla) {
            case 0:
                jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

            case 1:
                jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

            case 2:
                jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

            case 3:
                jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

            case 4:
                jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambio)));
                break;

        }

    }

    //Hace que los botones de los colores se presionen si dan a los botones predetermiandos de arriba.
    public void actualizaBotonColor() {
        float error = 0.15f;
        float hue = modelo.bombilla[modelo.numBombilla].getColor();
        float s = modelo.bombilla[modelo.numBombilla].getSaturacion();
        float b = modelo.bombilla[modelo.numBombilla].getBrillo();
        if (Math.abs(hue - 0) < error && Math.abs(s - 0) < error && Math.abs(b - 1) < error) {

            jToggleButtonBlanco.setSelected(true);

        } else if (Math.abs(hue - (60 / 360.0f)) < error && Math.abs(s - 1) < error && Math.abs(b - 1) < error) {

            jToggleButtonAmarillo.setSelected(true);

        } else if (Math.abs(hue - 0) < error && Math.abs(s - 1) < error && Math.abs(b - 1) < error) {

            jToggleButtonRojo.setSelected(true);

        } else if (Math.abs(hue - (240 / 360.0f)) < error && Math.abs(s - 1) < error && Math.abs(b - 1) < error) {

            jToggleButtonAzul.setSelected(true);

        } else if (Math.abs(hue - (120 / 360.0f)) < error && Math.abs(s - 1) < error && Math.abs(b - 1) < error) {

            jToggleButtonVerde.setSelected(true);

        } else {
            buttonGroup2.clearSelection();
        }

    }

    public void actualizaHabilitarColor() {
        if (modelo.bombilla[modelo.numBombilla].getEncendido()) {
            jToggleButtonBlanco.setEnabled(true);
            jToggleButtonAmarillo.setEnabled(true);
            jToggleButtonVerde.setEnabled(true);
            jToggleButtonAzul.setEnabled(true);
            jToggleButtonRojo.setEnabled(true);
            jButtonMasColores.setEnabled(true);

        } else {
            buttonGroup2.clearSelection();
            jToggleButtonBlanco.setEnabled(false);
            jToggleButtonAmarillo.setEnabled(false);
            jToggleButtonVerde.setEnabled(false);
            jToggleButtonAzul.setEnabled(false);
            jToggleButtonRojo.setEnabled(false);
            jButtonMasColores.setEnabled(false);
            jButtonAtrasMasColores.setEnabled(false);
            controlador.mostrarColores(false);

        }
    }

    //Si cumple las propiedades los botones predeterminados se activa.
    //ESTA METIDA EN ACTUALIZA VISTA PERO SOLO SE CAMBIA SI EL USUARIO PULSA LA BOMBILLA
    //QUEDA ALGO RARUNO, NO SE DONDE PODEMOS METERLA
    public void activaBotonPredeterminado(String boton) {

        switch (boton) {
            case "encendidas":
                jToggleButtonEncendidas.setSelected(true);
                break;
            case "apagadas":
                jToggleButtonApagadas.setSelected(true);
                break;
            case "lectura":
                jToggleButtonLectura.setSelected(true);
                break;
            case "ambiente":
                jToggleButtonAmbiente.setSelected(true);
                break;
            case "ninguno":
                buttonGroup1.clearSelection();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonAmpliarLetra;
    private javax.swing.JButton jButtonAtrasMasColores;
    private javax.swing.JButton jButtonContraste;
    private javax.swing.JButton jButtonMasColores;
    private javax.swing.JButton jButtonReducirLetra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelImagenColores;
    private javax.swing.JLabel jLabelIntensidad;
    private javax.swing.JLabel jLabelTextoIntensidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JPanel jPanelInterruptor;
    private javax.swing.JPanel jPanelLuz;
    private javax.swing.JPanel jPanelMasColores;
    private javax.swing.JPanel jPanelPredeterminados;
    private javax.swing.JPanel jPanelPropiedades;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButtonAmarillo;
    private javax.swing.JToggleButton jToggleButtonAmbiente;
    private javax.swing.JToggleButton jToggleButtonApagadas;
    private javax.swing.JToggleButton jToggleButtonAzul;
    private javax.swing.JToggleButton jToggleButtonBlanco;
    private javax.swing.JToggleButton jToggleButtonEncendidas;
    private javax.swing.JToggleButton jToggleButtonEncendido;
    private javax.swing.JToggleButton jToggleButtonLectura;
    private javax.swing.JToggleButton jToggleButtonRojo;
    private javax.swing.JToggleButton jToggleButtonVerde;
    // End of variables declaration//GEN-END:variables

}
