package ui.domotica.calefaccion;

import ui.Main;
import ui.Modelo;

/**
 *
 * @author Hernando Brecht, Rebeca.
 * @author Herruzo Herrero, Juan.
 */
public class VistaCalefaccion extends javax.swing.JFrame {

    // El tamaño del slider es de 8 px extra por cada lado, por lo que para 
    // hacer cálculos precisos de posición necesitamos evitarlos.
    private final int TAM_EXTRA_SLIDER = 8;

    private ControladorCalefaccion controlador;
    private Modelo modelo;

    public VistaCalefaccion() {
        initComponents();
        modelo = Main.getStateMachineDomotica().getModelo();
        controlador = new ControladorCalefaccion(this, modelo);
        actualizaEncendido();
        actualizaCalor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCentral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jButtonMenos = new javax.swing.JButton();
        jToggleButtonEncender = new javax.swing.JToggleButton();
        jButtonMas = new javax.swing.JButton();
        jPanelBotones = new javax.swing.JPanel();
        jButtonCalefaccion = new javax.swing.JButton();
        jButtonLuz = new javax.swing.JButton();
        jButtonPersiana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 310));
        setResizable(false);

        jPanel4.setMinimumSize(new java.awt.Dimension(650, 40));
        jPanel4.setName(""); // NOI18N

        jButtonHome.setBackground(new java.awt.Color(255, 153, 153));
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/home.png"))); // NOI18N
        jButtonHome.setMaximumSize(new java.awt.Dimension(94, 60));
        jButtonHome.setMinimumSize(new java.awt.Dimension(94, 60));
        jButtonHome.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jLabelTitulo.setBackground(new java.awt.Color(255, 204, 204));
        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Calefacción");
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(51, 70));
        jLabelTitulo.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelCentral.setPreferredSize(new java.awt.Dimension(650, 358));

        jPanel2.setMinimumSize(new java.awt.Dimension(220, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(220, 300));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jSlider1.setMajorTickSpacing(2);
        jSlider1.setMaximum(32);
        jSlider1.setMinimum(4);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(20);
        jSlider1.setPreferredSize(new java.awt.Dimension(400, 60));
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSlider1MousePressed(evt);
            }
        });
        jPanel2.add(jSlider1);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 100));

        jButtonMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/menos.png"))); // NOI18N
        jButtonMenos.setPreferredSize(new java.awt.Dimension(140, 140));
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jToggleButtonEncender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/on_off.png"))); // NOI18N
        jToggleButtonEncender.setPreferredSize(new java.awt.Dimension(140, 140));
        jToggleButtonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEncenderActionPerformed(evt);
            }
        });

        jButtonMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/mas.png"))); // NOI18N
        jButtonMas.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonMas.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonMas.setPreferredSize(new java.awt.Dimension(140, 140));
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jToggleButtonEncender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jToggleButtonEncender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBotones.setMinimumSize(new java.awt.Dimension(650, 40));
        jPanelBotones.setPreferredSize(new java.awt.Dimension(650, 60));
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 3, 12, 0));

        jButtonCalefaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/calefaccion.png"))); // NOI18N
        jButtonCalefaccion.setEnabled(false);
        jButtonCalefaccion.setMaximumSize(new java.awt.Dimension(210, 60));
        jButtonCalefaccion.setMinimumSize(new java.awt.Dimension(210, 60));
        jButtonCalefaccion.setPreferredSize(new java.awt.Dimension(210, 60));
        jButtonCalefaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalefaccionActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonCalefaccion);

        jButtonLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/luz.png"))); // NOI18N
        jButtonLuz.setMaximumSize(new java.awt.Dimension(210, 60));
        jButtonLuz.setMinimumSize(new java.awt.Dimension(210, 60));
        jButtonLuz.setPreferredSize(new java.awt.Dimension(210, 60));
        jButtonLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuzActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonLuz);

        jButtonPersiana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/assets/persiana.png"))); // NOI18N
        jButtonPersiana.setMaximumSize(new java.awt.Dimension(210, 60));
        jButtonPersiana.setMinimumSize(new java.awt.Dimension(210, 60));
        jButtonPersiana.setPreferredSize(new java.awt.Dimension(210, 60));
        jButtonPersiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersianaActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonPersiana);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuzActionPerformed
        controlador.luz();
    }//GEN-LAST:event_jButtonLuzActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        controlador.home();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonCalefaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalefaccionActionPerformed
        controlador.calefaccion();
    }//GEN-LAST:event_jButtonCalefaccionActionPerformed

    private void jButtonPersianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersianaActionPerformed
        controlador.persiana();
    }//GEN-LAST:event_jButtonPersianaActionPerformed

    private void jToggleButtonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEncenderActionPerformed
        controlador.encender();
    }//GEN-LAST:event_jToggleButtonEncenderActionPerformed

    private void jSlider1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MousePressed

        controlador.cambiarTemperatura(posicionSlider(evt.getX()));
    }//GEN-LAST:event_jSlider1MousePressed

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        controlador.cambiarTemperatura(modelo.getTemperatura() + 1);
    }//GEN-LAST:event_jButtonMasActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        controlador.cambiarTemperatura(modelo.getTemperatura() - 1);
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged

        controlador.cambiarTemperatura(posicionSlider(evt.getX()));
    }//GEN-LAST:event_jSlider1MouseDragged

    /*Actuliza el botón de encendido para pulsarlo cuando esté encendido.*/
    public void actualizaEncendido() {
        if (modelo.getcalEncendida()) {
            jToggleButtonEncender.setSelected(true);
        } else {
            jToggleButtonEncender.setSelected(false);
        }

    }

 
    /*Actualiza el Slider para ponerlo en la posición que corresponda.*/
    public void actualizaCalor() {
        jSlider1.setValue(modelo.temperatura);
    }

    /*
        Para calcular el valor se quitan los primeros 8 px del slider y los 8 últimos,
        después comprobamos donde se ha pulsado en el slider y se proporciona
        al tamaño del slider.
     */
    public int posicionSlider(int x) {
        return (int) ((jSlider1.getMinimum()
                + ((x - TAM_EXTRA_SLIDER) / ((jSlider1.getWidth() - TAM_EXTRA_SLIDER * 2) * 1.0))
                * (jSlider1.getMaximum() - jSlider1.getMinimum())) + 0.5);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalefaccion;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLuz;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonPersiana;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton jToggleButtonEncender;
    // End of variables declaration//GEN-END:variables
}
